keys:
  - &admin_mhelton age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
  - &bb age1tjjl492ww3uq9gtsxrwtwxkuptskv2cq457aj38a967hcyax8fvs7mg502
  - &imubit-morganh-dell age1dpgjk69at03mtsrkqshcr9hfxla6t05zejwvask7tj9mx44e2ejsjae2tj
  - &bob age1w0fmtklwf4jdr3rzxx6jd3qrdc5j433vsx0j682py2yvc4vpn5ysl03jdx
creation_rules:
  - path_regex: secrets.*$
    key_groups:
    - age:
      - *admin_mhelton
      - *bb
      - *imubit-morganh-dell
      - *bob
