keys:
  - &admin_mhelton age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
  - &L-MHELTON age1tham3z72m9k543e4m7rsjpgxkylsnh3uur3ftema6c3zl9d36ezs496kwk
  - &bob age1w0fmtklwf4jdr3rzxx6jd3qrdc5j433vsx0j682py2yvc4vpn5ysl03jdx
creation_rules:
  - path_regex: secrets.*$
    key_groups:
      - age:
          - *admin_mhelton
          - *L-MHELTON
          - *bob
