name: build NixOS configuration
on:
  workflow_dispatch:
    inputs:
      hostname:
        required: true
        type: string
        default: tomservo
  push:

jobs:
  build_nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v8
      - uses: ryanccn/attic-action@v0
        with:
          cache: ${{ secrets.ATTIC_CACHE }}
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          token: ${{ secrets.ATTIC_TOKEN }}
          skip-push: true
      - name: build tomservo
        run: |
          nix run github:Mic92/nix-fast-build -- --flake .#nixosConfigurations.tomservo.config.system.build.toplevel --skip-cached --eval-workers 2 --debug
          attic push r2d2 result

