name: build NixOS configurations for PRs

on:
  workflow_dispatch:
  pull_request:

jobs:
  build_hosts:
    strategy:
      matrix:
        hosts: ["tomservo", "bob", "durandal"]
    secrets: inherit
    steps:
      uses: ./.github/workflows/build-configuration.yaml
      with:
        hostname: ${{ matrix.hosts }}


