name: build NixOS configurations for PRs

on:
  pull_request:

jobs:
  build_hosts:
    strategy:
      matrix:
        hosts: ["tomservo", "bob"]
    secrets: inherit
    uses: ./.github/workflows/build-configuration.yaml
    with:
      hostname: ${{ matrix.hosts }}


