name: build NixOS configuration
on:
  workflow_call:
    inputs:
      hostname:
        required: true
        type: string

jobs:
  build_nixos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v8
      - uses: ryanccn/attic-action@v0
        with:
          cache: ${{ secrets.ATTIC_CACHE }}
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          token: ${{ secrets.ATTIC_TOKEN }}
          skip-push: true
      - name: build ${{ inputs.hostname }}
        run: |
          nix run github:Mic92/nix-fast-build -- --flake .#nixosConfigurations.${{ inputs.hostname }}.config.system.build.toplevel --skip-cached --eval-workers 2 --no-nom
          attic push ${{ secrets.ATTIC_CACHE }} result*
