name: build configurations

on:
  workflow_dispatch:

jobs:
  build_hosts:
    strategy:
      fail-fast: false
      matrix:
        hosts: ["tomservo", "bob", "durandal"]
    secrets: inherit
    uses: ./.github/workflows/build-nixos-configuration.yaml
    with:
      hostname: ${{ matrix.hosts }}


