name: build NixOS configurations

on:
  pull_request:

jobs:
  build_hosts:
    strategy:
      matrix:
        hosts: ["tomservo", "bob", "durandal"]
    secrets: inherit
    uses: ./.github/workflows/build-nixos-configuration.yaml
    with:
      hostname: ${{ matrix.hosts }}


